### PR TITLE
Manually add 8.1.4 handled for the modules list #36

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Similar to https://github.com/PrestaShop/distribution-api/pull/36
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | Verify https://integration-api.prestashop-project.org/modules/8.1.4 works after PR was has been on integration environment using `integration-deployment` label

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by matks** [comment]
CI is OK, I add `integration-deployment` label to deploy in integration environment

**Comment by matks** [comment]
https://github.com/PrestaShop/distribution-api/actions/runs/7738788735/job/21100325005 Integration deployment failed you are going too fast @Hlavtox

**Comment by matks** [comment]
Ah, the Integration job failed because I submitted a PR from my fork so the secrets were not available.

**Comment by Hlavtox** [comment]
You said CI is OK!!!! :D

**Comment by matks** [comment]
@Hlavtox CI was OK, not tests on integration env

Following merge, the code was deployed on preprod environment so we can verify https://preprod-api.prestashop-project.org/modules/8.1.4 works

It does

**Comment by matks** [comment]
Following the deploy process described in the README, https://github.com/PrestaShop/distribution-api/actions/runs/7739003559 release is done

**Comment by matks** [comment]
8.1.4 is now acknowledged by Distribution API https://api.prestashop-project.org/modules/8.1.4

**Pull request merged**
