### PR TITLE
Don't rely on deprecated save-state and set-output commands

### PR DESCRIPTION
**Pull request by JMorinPS**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Apply https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | PrestaShop Corp
| How to test?      | CI should run as expected

### CODE REVIEW

**Review by elodie-bil3 — APPROVED** [review]

**Review by matks — CHANGES_REQUESTED** [review]
@JMorinPS I updated the PR title and description to make it clear what is being done here 🎐 

CI is red, could you please verify?

**Comment by JMorinPS** [comment]
Looks like that job named `PHP Static Analysis` is waiting for a specific path 
`Input required and not supplied: path`

**Comment by JMorinPS** [comment]
All good

**Review by boherm — APPROVED** [review]

**Comment by matks** [comment]
Good for me 😉 thank you @JMorinPS

**Pull request merged**
