### PR TITLE
Automatically add next versions

### PR DESCRIPTION
**Pull request by Hlavtox**
Replacement of https://github.com/PrestaShop/distribution-api/pull/39.

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Automatically creates endpoint for next major, patches of current major and patches for previous major.
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | 

Before:
1.7.8.10
8.0.4
8.0.5
8.1.3
8.1.4
9.0.0

After:
1.7.8.10
8.0.4
8.0.5
8.1.3
8.1.4
9.0.0
**10.0.0 // Added
9.0.1 // Added
9.1.0 // Added
8.1.5 // Added
8.2.0 // Added**

### CODE REVIEW

**Comment by Hlavtox** [comment]
@matks @jolelievre Added tests to test getting version numbers. Added tests to test getting next major, minor and patch versions. Moved the PR into upstream.

Can you tell me how can I now test the deployment? https://preprod-api.prestashop-project.org/modules/8.2.0 still doesn't contain nothing. 🤷‍♂️

**Comment by matks** [comment]
> @matks @jolelievre Added tests to test getting version numbers. Added tests to test getting next major, minor and patch versions. Moved the PR into upstream.
> 
> Can you tell me how can I now test the deployment? https://preprod-api.prestashop-project.org/modules/8.2.0 still doesn't contain nothing. 🤷‍♂️

## Test and deployment

Read https://github.com/PrestaShop/distribution-api?tab=readme-ov-file#workflow

- when you open a PR (on the upstream repo, like this one) you can add the `integration-deployment` to deploy the code on INTEGRATION environment integration-api.prestashop-project.org
- when the PR is merged, this will deploy the code of `main` on PREPROD environment preprod-api.prestashop-project.org
- when we do a GitHub release, this will deploy the code of the release tag on PROD environment api.prestashop-project.org

Your code should now be available on integration-api.prestashop-project.org

## Looking at integration for your PR

On https://integration-api.prestashop-project.org/ I can see that
- https://integration-api.prestashop-project.org/modules/8.0.5 is available
- https://integration-api.prestashop-project.org/modules/8.0.6 is NOT available
- https://integration-api.prestashop-project.org/modules/8.1.3 is available
- https://integration-api.prestashop-project.org/modules/8.1.4 is NOT available
- https://integration-api.prestashop-project.org/modules/9.0.0 is available
- https://integration-api.prestashop-project.org/modules/9.1.0 is NOT available

## About logic

> 10.0.0 // Added
9.0.1 // Added
9.1.0 // Added
8.1.5 // Added
8.2.0 // Added

I think you went too far 😁 I don't think we need 9.1.0 right now you're 1 year early.

**Comment by Hlavtox** [comment]
@matks The logic has been fixed, I forgot comparator sign.

**Available endpoints:**
- https://integration-api.prestashop-project.org/modules/8.1.4
- https://integration-api.prestashop-project.org/modules/8.2.0
- https://integration-api.prestashop-project.org/modules/9.0.0

**Review by matks — CHANGES_REQUESTED** [review]
@Hlavtox Your tests do not cover the generation logic. Your tests do not verify that, if the "highest found version" is 8.1.4, then development versions 8.1.5, 8.2.0 et 9.0.0 will be added. This is what I insist on having covered.

Your tests simply verify the model `PrestaShop` logic which is basically "how to use implode" ^^

We want to put tests in place not only to catch bugs now but also to catch bugs in the future, when the next developer comes and modifies this logic, and breaks something.

Do you need help to run the tests?

**Comment by Hlavtox** [comment]
@matks Mathieu could you write the tests please? I don't want to spend more time with it. 🙏

**Review by matks — APPROVED** [review]
Looks good to me

**Pull request merged**
